/**
 * Preserve custom JSX components generated by the atom pipeline.
 * Earlier versions flattened capitalized tags into divs, which destroyed
 * the assembled component tree and produced hollow previews.
 */
function replaceCustomComponentsWithDiv(code: string): string {
  return code;
}

/**
 * Fix incomplete JSX attribute handlers like onChange={(e) => func(
 * by detecting unclosed parentheses within attribute expressions and closing them.
 */
function fixIncompleteAttributeHandlers(code: string): string {
  let fixed = code;
  const bareTagLineRE =
    /^\s*(\/?)(main|header|footer|section|article|div|form|label|input|button|p|span|ul|ol|li|h[1-6])\b([^<]*)$/i;

  // Scan for incomplete handlers by looking for lines ending with incomplete expressions
  const lines = fixed.split("\n");
  for (let i = 0; i < lines.length; i++) {
    let line = lines[i];

    // Fix dropped '<' on JSX tag lines like "input" or "/main>".
    const bareTagMatch = line.match(bareTagLineRE);
    if (bareTagMatch && !line.trimStart().startsWith("<")) {
      const [, slash, tag, rest] = bareTagMatch;
      const suffix = rest.trimEnd().endsWith(">") ? rest : `${rest}>`;
      line = `<${slash}${tag}${suffix}`;
      lines[i] = line;
    }

    // Detect lines with incomplete arrow functions or method calls:
    // e.g., "onChange={(e) => setUsername(e.target.value"
    // Pattern: attribute={...function call without closing paren/brace
    if (
      line.includes("onChange=") ||
      line.includes("onClick=") ||
      line.includes("onSubmit=")
    ) {
      const hasOpeningBrace = line.includes("{");
      const hasClosingBrace = line.includes("}");
      const openParens = (line.match(/\(/g) || []).length;
      const closeParens = (line.match(/\)/g) || []).length;

      if (hasOpeningBrace && !hasClosingBrace) {
        const parenFix =
          openParens > closeParens ? ")".repeat(openParens - closeParens) : "";
        lines[i] = `${line}${parenFix}}`;
        continue;
      }

      const unclosedParenMatch = line.match(/\(\w+\)\s*=>\s*\w+\([^)]*$/);
      if (unclosedParenMatch) {
        // This line has an incomplete arrow function call; close it
        lines[i] = line + ")";
      }
    }

    // Also check for incomplete object/array literals in attributes
    if (line.match(/\w+=\{[^}]*\(\s*$/)) {
      lines[i] = line + ")";
    }
  }

  fixed = lines.join("\n");

  // Additional scan: look for single-line JSX start tags that never close.
  // Keep the tag name intact; only append a self-close when the line is clearly a tag start.
  fixed = fixed.replace(
    /^\s*<([A-Za-z][\w:-]*)([^>]*?)\s*$/gm,
    (_match, tagName: string, attrs: string) => {
      if (attrs.includes("{") && !attrs.includes("}")) {
        return _match;
      }
      return `<${tagName}${attrs} />`;
    },
  );

  // Final aggressive scan: balance all JSX tags globally
  // Count opening/closing tags and add missing closers
  const selfClosingTags = new Set(["input", "img", "br", "hr", "meta", "link"]);
  const openTags: string[] = [];
  const tagRegex = /<(\/?)([A-Za-z][\w:-]*)[^>]*>/g;
  let match;

  while ((match = tagRegex.exec(fixed)) !== null) {
    const isClose = !!match[1];
    const tagName = match[2].toLowerCase();

    if (!isClose && !selfClosingTags.has(tagName)) {
      openTags.push(tagName);
    } else if (isClose) {
      if (openTags.length > 0 && openTags[openTags.length - 1] === tagName) {
        openTags.pop();
      }
    }
  }

  // Close remaining open tags
  if (openTags.length > 0) {
    const closingTags = openTags
      .reverse()
      .map((tag) => `</${tag}>`)
      .join("");
    fixed = fixed.trimRight() + "\n" + closingTags;
  }

  return fixed;
}

/**
 * Fix orphaned attributes: when attributes appear on lines after a self-closing tag.
 * Example (bad):
 *   <input />
 *   type="text"
 *   placeholder="..."
 * Should be:
 *   <input type="text" placeholder="..." />
 */
function fixOrphanedAttributes(code: string): string {
  const lines = code.split("\n");
  const result: string[] = [];

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trim();

    // Check if this line is a self-closing tag
    if (
      trimmed.match(
        /^<(input|button|img|br|hr|meta|link|area|base|col|embed|source|track|wbr)\s*\/?>/i,
      )
    ) {
      // Collect attributes from following lines
      const attributes: string[] = [];
      let j = i + 1;

      while (j < lines.length) {
        const nextLine = lines[j].trim();
        // Check if the line looks like JSX attribute (key="value" or key={...})
        if (nextLine.match(/^[\w-]+=["'{]/)) {
          attributes.push(nextLine);
          j++;
        } else {
          break;
        }
      }

      // If we found attributes, merge them into the tag and skip those lines
      if (attributes.length > 0) {
        const tagMatch = trimmed.match(/^(<\w+)(\s*\/?)>/);
        if (tagMatch) {
          const [, openTag, slash] = tagMatch;
          const merged = `${openTag} ${attributes.join(" ")}${slash || " "}>`;
          result.push(line.replace(trimmed, merged));
          i = j - 1; // Skip the attribute lines
        } else {
          result.push(line);
        }
      } else {
        result.push(line);
      }
    } else {
      result.push(line);
    }
  }

  return result.join("\n");
}

export function autoCloseJsx(code: string): string {
  if (!code || typeof code !== "string") return code;

  let fixed = code;

  // First, replace any custom components with divs to prevent validation errors
  fixed = replaceCustomComponentsWithDiv(fixed);

  // Fix incomplete JSX attribute handlers: detect patterns like `onChange={(e) => func(`
  // and close them properly before they break JSX parsing.
  // Pattern: attribute="...( ... (" with unmatched parens within the attribute value.
  fixed = fixIncompleteAttributeHandlers(fixed);

  // Fix orphaned attributes that appear after self-closing tags
  fixed = fixOrphanedAttributes(fixed);

  // Balance simple braces and parentheses
  const openBraces = (fixed.match(/\{/g) || []).length;
  const closeBraces = (fixed.match(/\}/g) || []).length;
  if (openBraces > closeBraces) {
    fixed += "\n" + "}".repeat(openBraces - closeBraces);
  }

  const openParens = (fixed.match(/\(/g) || []).length;
  const closeParens = (fixed.match(/\)/g) || []).length;
  if (openParens > closeParens) {
    fixed += ")".repeat(openParens - closeParens);
  }

  // Common JSX tags to ensure closing tags for
  const tags = [
    "div",
    "p",
    "span",
    "button",
    "section",
    "header",
    "footer",
    "main",
    "ul",
    "ol",
    "li",
    "form",
    "label",
    "article",
  ];

  const toClose: string[] = [];

  for (const tag of tags) {
    const openRegex = new RegExp(`<${tag}(\\s|>|\\/>)`, "gi");
    const selfClosingRegex = new RegExp(`<${tag}[^>]*\\/\\s*>`, "gi");
    const closeRegex = new RegExp(`</${tag}>`, "gi");

    const opens = (fixed.match(openRegex) || []).length;
    const closes = (fixed.match(closeRegex) || []).length;
    const selfCloses = (fixed.match(selfClosingRegex) || []).length;

    const effectiveOpens = Math.max(0, opens - selfCloses);
    if (effectiveOpens > closes) {
      const missing = effectiveOpens - closes;
      for (let i = 0; i < missing; i++) toClose.push(tag);
    }
  }

  if (toClose.length > 0) {
    // Append closing tags in reverse order (naive stack heuristic)
    fixed +=
      "\n" +
      toClose
        .reverse()
        .map((t) => `</${t}>`)
        .join("\n");
  }

  // Final aggressive pass: close any remaining unbalanced tags by counting
  // open vs close occurrences for simple tag names and appending missing closers.
  try {
    const simpleTagRE = /<([A-Za-z][\w:-]*)([^>/]*?)>/g;
    const selfCloseRE = /<([A-Za-z][\w:-]*)([^>]*?)\/\s*>/g;
    const closeTagRE = /<\/([A-Za-z][\w:-]*)>/g;

    const opens: Record<string, number> = {};
    const closes: Record<string, number> = {};

    let m: RegExpExecArray | null;
    while ((m = simpleTagRE.exec(fixed))) {
      const tag = m[1].toLowerCase();
      opens[tag] = (opens[tag] || 0) + 1;
    }
    while ((m = selfCloseRE.exec(fixed))) {
      const tag = m[1].toLowerCase();
      // Count self-closing tags as a close
      closes[tag] = (closes[tag] || 0) + 1;
      // Reduce opens since they were counted above
      opens[tag] = Math.max(0, (opens[tag] || 1) - 1);
    }
    while ((m = closeTagRE.exec(fixed))) {
      const tag = m[1].toLowerCase();
      closes[tag] = (closes[tag] || 0) + 1;
    }

    const missingClosers: string[] = [];
    for (const tag of Object.keys(opens)) {
      const openCount = opens[tag] || 0;
      const closeCount = closes[tag] || 0;
      if (openCount > closeCount) {
        for (let i = 0; i < openCount - closeCount; i++)
          missingClosers.push(tag);
      }
    }

    if (missingClosers.length > 0) {
      fixed +=
        "\n" +
        missingClosers
          .reverse()
          .map((t) => `</${t}>`)
          .join("\n");
    }
  } catch (e) {
    // swallow any unexpected errors in the aggressive fixer
  }

  // Ensure common endings for React files
  // If an export default is present but missing trailing semicolon, leave it alone.
  // Return the fixed code
  return fixed;
}
